-- Auralink 2.0 data foundation.
--
-- Public IDs are canonical UUID strings generated by the application. Code,
-- modality, provider, visibility, and status values intentionally remain
-- extensible strings; this migration does not constrain them to closed lists.

CREATE TABLE media_assets (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    public_id TEXT NOT NULL,
    owner_user_id INTEGER,
    storage_key VARCHAR(1024) NOT NULL,
    original_filename VARCHAR(512) NOT NULL,
    mime_type VARCHAR(255),
    file_size BIGINT,
    sha256 VARCHAR(64),
    width INTEGER,
    height INTEGER,
    duration_seconds REAL,
    asset_type VARCHAR(64) NOT NULL,
    semantic_type VARCHAR(64) NOT NULL,
    source_type VARCHAR(64) NOT NULL,
    visibility VARCHAR(64) NOT NULL,
    status VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_media_assets_public_id UNIQUE (public_id),
    CONSTRAINT uq_media_assets_storage_key UNIQUE (storage_key),
    CONSTRAINT fk_media_assets_owner_user
        FOREIGN KEY (owner_user_id) REFERENCES users (id) ON DELETE RESTRICT
);

CREATE INDEX idx_media_assets_owner_created
    ON media_assets (owner_user_id, created_at);
CREATE INDEX idx_media_assets_type_status
    ON media_assets (asset_type, semantic_type, status);
CREATE INDEX idx_media_assets_sha256
    ON media_assets (sha256);

CREATE TABLE paintings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    public_id TEXT NOT NULL,
    source_key VARCHAR(1024) NOT NULL,
    source_sequence VARCHAR(64),
    image_storage_name VARCHAR(512) NOT NULL,
    title VARCHAR(512),
    author_name VARCHAR(255),
    author_birth_year VARCHAR(64),
    author_birth_place VARCHAR(512),
    author_school VARCHAR(255),
    creation_year VARCHAR(255),
    creation_dynasty_raw VARCHAR(255),
    creation_dynasty_normalized VARCHAR(255),
    actual_size VARCHAR(255),
    collection_institution VARCHAR(512),
    category VARCHAR(255),
    subject VARCHAR(512),
    painting_school VARCHAR(255),
    style TEXT,
    color TEXT,
    composition TEXT,
    artistic_conception TEXT,
    brushwork TEXT,
    ink_method TEXT,
    painting_material TEXT,
    pigment TEXT,
    seal TEXT,
    cultural_symbol TEXT,
    generated_text TEXT,
    music_scene_description TEXT,
    collection_platform VARCHAR(512),
    image_asset_id INTEGER,
    image_available BOOLEAN NOT NULL DEFAULT 0,
    visible_in_gallery BOOLEAN NOT NULL DEFAULT 1,
    status VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_paintings_public_id UNIQUE (public_id),
    CONSTRAINT uq_paintings_source_key UNIQUE (source_key),
    CONSTRAINT fk_paintings_image_asset
        FOREIGN KEY (image_asset_id) REFERENCES media_assets (id) ON DELETE SET NULL
);

CREATE INDEX idx_paintings_image_storage_name
    ON paintings (image_storage_name);
CREATE INDEX idx_paintings_gallery_status
    ON paintings (visible_in_gallery, status);
CREATE INDEX idx_paintings_dynasty
    ON paintings (creation_dynasty_normalized);
CREATE INDEX idx_paintings_category
    ON paintings (category);
CREATE INDEX idx_paintings_author_name
    ON paintings (author_name);
CREATE INDEX idx_paintings_image_asset
    ON paintings (image_asset_id);

CREATE TABLE catalog_import_runs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    public_id TEXT NOT NULL,
    source_name VARCHAR(512) NOT NULL,
    source_sha256 VARCHAR(64) NOT NULL,
    total_rows INTEGER NOT NULL DEFAULT 0,
    inserted_rows INTEGER NOT NULL DEFAULT 0,
    updated_rows INTEGER NOT NULL DEFAULT 0,
    unchanged_rows INTEGER NOT NULL DEFAULT 0,
    matched_images INTEGER NOT NULL DEFAULT 0,
    missing_images INTEGER NOT NULL DEFAULT 0,
    orphan_images INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(64) NOT NULL,
    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP,
    error_message TEXT,
    CONSTRAINT uq_catalog_import_runs_public_id UNIQUE (public_id)
);

CREATE INDEX idx_catalog_import_runs_status_started
    ON catalog_import_runs (status, started_at);
CREATE INDEX idx_catalog_import_runs_source_sha256
    ON catalog_import_runs (source_sha256);

CREATE TABLE painting_guides (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    public_id TEXT NOT NULL,
    painting_id INTEGER NOT NULL,
    result_json TEXT,
    source_hash VARCHAR(64),
    status VARCHAR(64) NOT NULL,
    generated_at TIMESTAMP,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_painting_guides_public_id UNIQUE (public_id),
    CONSTRAINT uq_painting_guides_painting UNIQUE (painting_id),
    CONSTRAINT fk_painting_guides_painting
        FOREIGN KEY (painting_id) REFERENCES paintings (id) ON DELETE RESTRICT
);

CREATE INDEX idx_painting_guides_status
    ON painting_guides (status);
CREATE INDEX idx_painting_guides_source_hash
    ON painting_guides (source_hash);

CREATE TABLE painting_favorites (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    public_id TEXT NOT NULL,
    user_id INTEGER NOT NULL,
    painting_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_painting_favorites_public_id UNIQUE (public_id),
    CONSTRAINT uq_painting_favorites_user_painting UNIQUE (user_id, painting_id),
    CONSTRAINT fk_painting_favorites_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_painting_favorites_painting
        FOREIGN KEY (painting_id) REFERENCES paintings (id) ON DELETE RESTRICT
);

CREATE INDEX idx_painting_favorites_user_created
    ON painting_favorites (user_id, created_at);
CREATE INDEX idx_painting_favorites_painting_user
    ON painting_favorites (painting_id, user_id);

CREATE TABLE user_workflows (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    public_id TEXT NOT NULL,
    user_id INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    graph_json TEXT NOT NULL,
    schema_version INTEGER NOT NULL,
    status VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_user_workflows_public_id UNIQUE (public_id),
    CONSTRAINT fk_user_workflows_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
);

CREATE INDEX idx_user_workflows_user_status_updated
    ON user_workflows (user_id, status, updated_at);

CREATE TABLE creations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    public_id TEXT NOT NULL,
    user_id INTEGER NOT NULL,
    workflow_id INTEGER,
    workflow_snapshot TEXT NOT NULL,
    source_modality VARCHAR(64) NOT NULL,
    source_text TEXT,
    source_painting_id INTEGER,
    source_asset_id INTEGER,
    status VARCHAR(64) NOT NULL,
    final_modality VARCHAR(64),
    final_asset_id INTEGER,
    final_output_json TEXT,
    created_at TIMESTAMP NOT NULL,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    CONSTRAINT uq_creations_public_id UNIQUE (public_id),
    CONSTRAINT fk_creations_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_creations_workflow
        FOREIGN KEY (workflow_id) REFERENCES user_workflows (id) ON DELETE SET NULL,
    CONSTRAINT fk_creations_source_painting
        FOREIGN KEY (source_painting_id) REFERENCES paintings (id) ON DELETE RESTRICT,
    CONSTRAINT fk_creations_source_asset
        FOREIGN KEY (source_asset_id) REFERENCES media_assets (id) ON DELETE RESTRICT,
    CONSTRAINT fk_creations_final_asset
        FOREIGN KEY (final_asset_id) REFERENCES media_assets (id) ON DELETE RESTRICT
);

CREATE INDEX idx_creations_user_created
    ON creations (user_id, created_at);
CREATE INDEX idx_creations_user_status
    ON creations (user_id, status);
CREATE INDEX idx_creations_workflow
    ON creations (workflow_id);
CREATE INDEX idx_creations_source_painting
    ON creations (source_painting_id);
CREATE INDEX idx_creations_source_asset
    ON creations (source_asset_id);
CREATE INDEX idx_creations_final_asset
    ON creations (final_asset_id);

CREATE TABLE creation_steps (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    public_id TEXT NOT NULL,
    creation_id INTEGER NOT NULL,
    step_index INTEGER NOT NULL,
    node_id VARCHAR(255) NOT NULL,
    operation_code VARCHAR(128) NOT NULL,
    provider_code VARCHAR(128),
    input_modality VARCHAR(64) NOT NULL,
    output_modality VARCHAR(64) NOT NULL,
    input_json TEXT,
    parameters_json TEXT,
    output_json TEXT,
    input_asset_id INTEGER,
    output_asset_id INTEGER,
    status VARCHAR(64) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    error_code VARCHAR(128),
    error_message TEXT,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    CONSTRAINT uq_creation_steps_public_id UNIQUE (public_id),
    CONSTRAINT uq_creation_steps_creation_index UNIQUE (creation_id, step_index),
    CONSTRAINT fk_creation_steps_creation
        FOREIGN KEY (creation_id) REFERENCES creations (id) ON DELETE CASCADE,
    CONSTRAINT fk_creation_steps_input_asset
        FOREIGN KEY (input_asset_id) REFERENCES media_assets (id) ON DELETE RESTRICT,
    CONSTRAINT fk_creation_steps_output_asset
        FOREIGN KEY (output_asset_id) REFERENCES media_assets (id) ON DELETE RESTRICT
);

CREATE INDEX idx_creation_steps_creation_status
    ON creation_steps (creation_id, status);
CREATE INDEX idx_creation_steps_input_asset
    ON creation_steps (input_asset_id);
CREATE INDEX idx_creation_steps_output_asset
    ON creation_steps (output_asset_id);

CREATE TABLE creation_favorites (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    public_id TEXT NOT NULL,
    user_id INTEGER NOT NULL,
    creation_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_creation_favorites_public_id UNIQUE (public_id),
    CONSTRAINT uq_creation_favorites_user_creation UNIQUE (user_id, creation_id),
    CONSTRAINT fk_creation_favorites_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_creation_favorites_creation
        FOREIGN KEY (creation_id) REFERENCES creations (id) ON DELETE CASCADE
);

CREATE INDEX idx_creation_favorites_user_created
    ON creation_favorites (user_id, created_at);
CREATE INDEX idx_creation_favorites_creation_user
    ON creation_favorites (creation_id, user_id);
